name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
env:
  SERVICE: basket-api
  IMAGE: basket.api

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
