name: catalog-api-push

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
  
  pull_request:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
env:
  SERVICE: catalog-api
  IMAGE: catalog.api
  DOTNET_VERSION: 7.0.x
  PROJECT_PATH: Services/Catalog/Catalog.API
  TESTS_PATH: Services/Catalog/Catalog.UnitTests
  BRANCH: main

jobs:

  BuildAndPushLinux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}
