name: webmvc

on:
  workflow_dispatch:
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Web/WebMVC/**
    - .github/workflows/webmvc.yml
  
  pull_request:
    branches:
    - dev
    paths:
    
    - src/BuildingBlocks/**
    - src/Web/WebMVC/**
    - .github/workflows/webmvc.yml

env:
  SERVICE: webmvc
  IMAGE: webmvc

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
